// src/lib/placeholder-data.js

// DUMMY DATA: In a real app, this data would come from your backend API.

export const featuredProducts = [
  { id: 1, name: 'Glenfiddich 18 Year', type: 'Scotch Whisky', price: '₹8,500', image: 'https://placehold.co/400x400/1a202c/ffffff?text=Whisky', rating: 5 },
  { id: 2, name: 'Sula Sauvignon Blanc', type: 'White Wine', price: '₹1,200', image: 'https://placehold.co/400x400/4a5568/ffffff?text=Wine', rating: 4 },
  { id: 3, name: 'Bira 91 Blonde', type: 'Craft Beer', price: '₹180', image: 'https://placehold.co/400x400/2d3748/ffffff?text=Beer', rating: 4 },
  { id: 4, name: 'Absolut Vodka', type: 'Vodka', price: '₹2,100', image: 'https://placehold.co/400x400/718096/ffffff?text=Vodka', rating: 5 },
];

export const categories = [
  { name: 'Whisky', image: 'https://placehold.co/400x400/8B4513/FFFFFF?text=Whisky' },
  { name: 'Wine', image: 'https://placehold.co/400x400/800020/FFFFFF?text=Wine' },
  { name: 'Beer', image: 'https://placehold.co/400x400/FFD700/000000?text=Beer' },
  { name: 'Rum', image: 'https://placehold.co/400x400/A0522D/FFFFFF?text=Rum' },
  { name: 'Vodka', image: 'https://placehold.co/400x400/E0FFFF/000000?text=Vodka' },
  { name: 'Gin', image: 'https://placehold.co/400x400/008080/FFFFFF?text=Gin' },
];

export const featuredStores = [
    { name: 'Good Spirits', location: 'Jubilee Hills, Hyderabad', image: 'https://placehold.co/400x300/334155/ffffff?text=Good+Spirits' },
    { name: 'Main Street Liquor', location: 'Koramangala, Bengaluru', image: 'https://placehold.co/400x300/475569/ffffff?text=Main+St.+Liquor' },
    { name: 'The Wine Rack', location: 'Bandra West, Mumbai', image: 'https://placehold.co/400x300/52525b/ffffff?text=The+Wine+Rack' },
];

export const searchData = [
  { id: 1, name: 'Glenfiddich 18 Year', type: 'Scotch Whisky', category: 'whisky', price: '₹8,500' },
  { id: 2, name: 'Sula Sauvignon Blanc', type: 'White Wine', category: 'wine', price: '₹1,200' },
  { id: 3, name: 'Bira 91 Blonde', type: 'Craft Beer', category: 'beer', price: '₹180' },
  { id: 4, name: 'Absolut Vodka', type: 'Vodka', category: 'vodka', price: '₹2,100' },
  { id: 5, name: 'Old Monk', type: 'Dark Rum', category: 'rum', price: '₹800' },
  { id: 6, name: 'Greater Than Gin', type: 'Premium Gin', category: 'gin', price: '₹1,500' },
  { id: 7, name: 'Jacob\'s Creek Shiraz', type: 'Red Wine', category: 'wine', price: '₹1,400' },
  { id: 8, name: 'Kingfisher Ultra', type: 'Lager Beer', category: 'beer', price: '₹150' },
  { id: 9, name: 'Macallan 12 Year', type: 'Single Malt', category: 'whisky', price: '₹12,500' },
  { id: 10, name: 'Chandon Brut', type: 'Sparkling Wine', category: 'wine', price: '₹2,800' },
];

export const Stores = [
  { 
    id: 1, 
    name: 'Good Spirits', 
    location: 'Jubilee Hills, Hyderabad',
    address: '123 Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033',
    image: 'https://placehold.co/400x300/334155/ffffff?text=Good+Spirits',
    rating: 4.8,
    reviews: 324,
    deliveryTime: '45-60 min',
    deliveryFee: 49,
    minOrder: 500,
    isOpen: true,
    openTime: '10:00 AM - 11:00 PM',
    specialties: ['Premium Whisky', 'Imported Wine', 'Craft Beer'],
    offers: ['Free delivery on orders above ₹1000', '10% off on first order'],
    city: 'hyderabad',
    area: 'jubilee-hills',
    type: 'premium'
  },
  { 
    id: 2, 
    name: 'Main Street Liquor', 
    location: 'Koramangala, Bengaluru',
    address: '45 Main Street, Koramangala 5th Block, Bengaluru, Karnataka 560095',
    image: 'https://placehold.co/400x300/475569/ffffff?text=Main+St.+Liquor',
    rating: 4.5,
    reviews: 256,
    deliveryTime: '30-45 min',
    deliveryFee: 39,
    minOrder: 300,
    isOpen: true,
    openTime: '9:00 AM - 12:00 AM',
    specialties: ['Local Brands', 'Budget Friendly', 'Quick Delivery'],
    offers: ['Buy 2 Get 1 Free on select items', 'Free delivery on orders above ₹800'],
    city: 'bengaluru',
    area: 'koramangala',
    type: 'budget'
  },
  { 
    id: 3, 
    name: 'The Wine Rack', 
    location: 'Bandra West, Mumbai',
    address: '78 Hill Road, Bandra West, Mumbai, Maharashtra 400050',
    image: 'https://placehold.co/400x300/52525b/ffffff?text=The+Wine+Rack',
    rating: 4.9,
    reviews: 189,
    deliveryTime: '60-75 min',
    deliveryFee: 59,
    minOrder: 800,
    isOpen: true,
    openTime: '11:00 AM - 1:00 AM',
    specialties: ['Fine Wine', 'Champagne', 'Rare Spirits'],
    offers: ['Wine tasting events', '15% off on wine collections'],
    city: 'mumbai',
    area: 'bandra',
    type: 'luxury'
  },
  {
    id: 4,
    name: 'Delhi Drinks Depot',
    location: 'Connaught Place, New Delhi',
    address: 'Block A, Connaught Place, New Delhi, Delhi 110001',
    image: 'https://placehold.co/400x300/0f172a/ffffff?text=Delhi+Drinks',
    rating: 4.3,
    reviews: 412,
    deliveryTime: '40-55 min',
    deliveryFee: 45,
    minOrder: 400,
    isOpen: false,
    openTime: '10:00 AM - 11:30 PM',
    specialties: ['Wide Selection', 'Competitive Prices', 'Fast Service'],
    offers: ['Happy hours 4-7 PM', 'Bulk order discounts'],
    city: 'delhi',
    area: 'connaught-place',
    type: 'standard'
  },
  {
    id: 5,
    name: 'Chennai Cheers',
    location: 'T. Nagar, Chennai',
    address: '234 Usman Road, T. Nagar, Chennai, Tamil Nadu 600017',
    image: 'https://placehold.co/400x300/1e293b/ffffff?text=Chennai+Cheers',
    rating: 4.6,
    reviews: 298,
    deliveryTime: '50-65 min',
    deliveryFee: 55,
    minOrder: 600,
    isOpen: true,
    openTime: '10:30 AM - 11:00 PM',
    specialties: ['South Indian Brands', 'Traditional Spirits', 'Local Favorites'],
    offers: ['Festival special discounts', 'Loyalty program available'],
    city: 'chennai',
    area: 't-nagar',
    type: 'standard'
  },
  {
    id: 6,
    name: 'Pune Pour House',
    location: 'Koregaon Park, Pune',
    address: '56 North Main Road, Koregaon Park, Pune, Maharashtra 411001',
    image: 'https://placehold.co/400x300/334155/ffffff?text=Pune+Pour',
    rating: 4.7,
    reviews: 167,
    deliveryTime: '35-50 min',
    deliveryFee: 42,
    minOrder: 350,
    isOpen: true,
    openTime: '9:30 AM - 12:30 AM',
    specialties: ['Craft Beer', 'Artisanal Spirits', 'Curated Selection'],
    offers: ['Weekend specials', 'Student discounts available'],
    city: 'pune',
    area: 'koregaon-park',
    type: 'premium'
  },
  {
    id: 7,
    name: 'Kolkata Spirits Corner',
    location: 'Park Street, Kolkata',
    address: '89 Park Street, Kolkata, West Bengal 700016',
    image: 'https://placehold.co/400x300/475569/ffffff?text=Kolkata+Spirits',
    rating: 4.4,
    reviews: 203,
    deliveryTime: '45-60 min',
    deliveryFee: 48,
    minOrder: 450,
    isOpen: true,
    openTime: '10:00 AM - 11:00 PM',
    specialties: ['Bengali Favorites', 'Heritage Brands', 'Cultural Selection'],
    offers: ['Durga Puja specials', 'Group order discounts'],
    city: 'kolkata',
    area: 'park-street',
    type: 'standard'
  },
  {
    id: 8,
    name: 'Goa Beach Beverages',
    location: 'Calangute, Goa',
    address: '12 Beach Road, Calangute, Goa 403516',
    image: 'https://placehold.co/400x300/52525b/ffffff?text=Goa+Beach',
    rating: 4.8,
    reviews: 145,
    deliveryTime: '25-40 min',
    deliveryFee: 35,
    minOrder: 250,
    isOpen: true,
    openTime: '8:00 AM - 2:00 AM',
    specialties: ['Beach Vibes', 'Tropical Drinks', 'Party Essentials'],
    offers: ['Beach delivery available', 'Party packages'],
    city: 'goa',
    area: 'calangute',
    type: 'budget'
  }
];
